// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLYHDBxCSdQMe4IApBXw1wgc4xzdnaOl8',
    appId: '1:516134658936:web:0616d4087986ad3dc59e8d',
    messagingSenderId: '516134658936',
    projectId: 'app-quiz-fatecrp',
    authDomain: 'app-quiz-fatecrp.firebaseapp.com',
    storageBucket: 'app-quiz-fatecrp.appspot.com',
    measurementId: 'G-MC17949YP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3MLuzDY1wPhU7B9v5mQP6bdQa3kU-RAk',
    appId: '1:516134658936:android:4ef69dbdc8ed2278c59e8d',
    messagingSenderId: '516134658936',
    projectId: 'app-quiz-fatecrp',
    storageBucket: 'app-quiz-fatecrp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF1mqT28vJhSvYbh9OT_Wpd3MwJswHiNw',
    appId: '1:516134658936:ios:d9d6313d3562b085c59e8d',
    messagingSenderId: '516134658936',
    projectId: 'app-quiz-fatecrp',
    storageBucket: 'app-quiz-fatecrp.appspot.com',
    iosClientId: '516134658936-6g1ooigd8a67os0q3ii8js1rg9sgeijs.apps.googleusercontent.com',
    iosBundleId: 'com.example.appQuizFatec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF1mqT28vJhSvYbh9OT_Wpd3MwJswHiNw',
    appId: '1:516134658936:ios:d9d6313d3562b085c59e8d',
    messagingSenderId: '516134658936',
    projectId: 'app-quiz-fatecrp',
    storageBucket: 'app-quiz-fatecrp.appspot.com',
    iosClientId: '516134658936-6g1ooigd8a67os0q3ii8js1rg9sgeijs.apps.googleusercontent.com',
    iosBundleId: 'com.example.appQuizFatec',
  );
}
